## **Numpy Overview and Practice**

In [1]:
import numpy as np

### **Lists VS NumPy Arrays**

**Lists:**
- a = [1,3,5]
- b = [1,2,3]
- a*b = ERROR

**NumPy Arrays:**
- a = np.array([1,3,5])
- b = np.array([1,2,3])
- a*b = np.array([1,6,15])

**Efficiency Benefits of Numpy Arrays:**
- By storing bits of information together rather than including gaps of information, like lists do, NumPy arrays allow CPUS to take advantage of *SIMD (Single Instruction Multiple Data) Vector Processing*. This allows a computer to compute operations across all connected data points, as opposed to applying operations one at a time.
- Addtionally, in a process called *"Effective Cache Utilization"*, by storing the information together a computer can easily load in all pieces of data at once, as opposed to loading in only relevant pieces and having to reload data in later (like lists).

### **The Basics**

In [2]:
a = np.array([1,3,5], dtype='int8')
print(a, a.ndim, a.shape)
b = np.array([1,2,3])
print(b, b.ndim, b.shape)
c = a*b
print(c, c.ndim, c.shape)

[1 3 5] 1 (3,)
[1 2 3] 1 (3,)
[ 1  6 15] 1 (3,)


In [3]:
d = np.array([[3,6,9,12,11],[2,5,8,2,7]])
print(d, d.ndim, d.shape)
e = np.array([[11,15,3,23,45],[4,17,2,14,70]])
print(e, e.ndim, e.shape)
f = d*e
print(f, f.ndim, f.shape)

[[ 3  6  9 12 11]
 [ 2  5  8  2  7]] 2 (2, 5)
[[11 15  3 23 45]
 [ 4 17  2 14 70]] 2 (2, 5)
[[ 33  90  27 276 495]
 [  8  85  16  28 490]] 2 (2, 5)


In [27]:
for x in np.nditer(e):
    print(x)

11
3
3
23
45
4
4
2
14
70


In [4]:
itemsize = d.itemsize
size = d.size
total_size = size * itemsize
nbytes = d.nbytes
print(total_size, nbytes)

80 80


### **Accessing/Altering Elements, Rows, Columns**

In [5]:
elem1 = a[2]
elem2 = d[1, 3]
elem3 = e[0, -3]
print(elem1, elem2, elem3)

row = f[0, :]
col = f[:, 4]
print(row, col)

elem4 = d[0, 1:4:2]
print(elem4)

5 2 3
[ 33  90  27 276 495] [495 490]
[ 6 12]


In [6]:
d[0,4] = 15
print(d)

e[:,1] = [3,4]
print(e)

[[ 3  6  9 12 15]
 [ 2  5  8  2  7]]
[[11  3  3 23 45]
 [ 4  4  2 14 70]]


### **Initializing Different Arrays**

In [7]:
zeros = np.zeros((3,5))
print(zeros)

ones = np.ones((2, 4, 4))
print(ones)

full = np.full((2, 2), 75)
print(full)

full_like = np.full_like(a, 4)
print(full_like)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
[[75 75]
 [75 75]]
[4 4 4]


In [8]:
rand = np.random.rand(5, 3)
print(rand)

randint = np.random.randint(-5, 5, size=(3,3))
print(randint)

identity = np.identity(4)
print(identity)

[[0.36827756 0.70722853 0.49597187]
 [0.67909788 0.16467018 0.54993919]
 [0.20657895 0.03085401 0.7460448 ]
 [0.09756431 0.28629321 0.85247266]
 [0.12511054 0.75621178 0.45353805]]
[[ 4  1  1]
 [ 1 -1  3]
 [ 3 -3 -5]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [9]:
mylist = [0,1,2,3,4,5,6,7,8,9]
myarr = np.array(mylist)
print(myarr)

arange = np.arange(10)
print(arange)

arange_step = np.arange(0,10,2)
print(arange_step)

arr = np.array([1,2,3])
r1 = np.repeat(arr,3,axis=0)
print(r1)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[1 1 1 2 2 2 3 3 3]


### **Practice Array Manipulation**

In [10]:
base = np.ones((5,5), dtype='int16')
middle = np.zeros((3,3), dtype="int16")
middle[1,1] = 9
base[1:4,1:4] = middle
print(base)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


### **Mathematics**

In [21]:
a = np.array([1,2,3,4])
print((a + 2) / 2)

b = np.array([10,20,30,40])
print(b - a)

[1.5 2.  2.5 3. ]
[ 9 18 27 36]


In [22]:
sin = np.sin(a)
print(sin)

cos = np.cos(b)
print(cos)

log = np.log(b)
print(log)

[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[-0.83907153  0.40808206  0.15425145 -0.66693806]
[2.30258509 2.99573227 3.40119738 3.68887945]


In [20]:
sqrt = np.sqrt(b)
print(sqrt)

absolute = np.absolute(b)
print(absolute)

exponents = np.exp(b)
print(exponents)

test = np.arange(-5, 5)
sign = np.sign(test)
print(sign)

[[1.41421356 1.41421356]
 [1.41421356 1.41421356]
 [1.41421356 1.41421356]]
[[2 2]
 [2 2]
 [2 2]]
[[7.3890561 7.3890561]
 [7.3890561 7.3890561]
 [7.3890561 7.3890561]]
[-1 -1 -1 -1 -1  0  1  1  1  1]


In [15]:
stats = np.array([[1,2,3],[4,5,6]])
min = np.min(stats)
print(min)

max = np.max(stats, axis=1)
print(max)

sum = np.sum(stats, axis=0)
print(sum)

1
[3 6]
[5 7 9]


#### ***Linear Algebra***

In [13]:
# Matrix Multiplication
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [14]:
# Find the Determinant
c = np.identity(3)
np.linalg.det(c)

1.0

### **Reorganizing Arrays**

In [16]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((2,2,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [17]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [18]:
# Horizontal stacking vectors
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### **Copy VS View**

In [25]:
np1 = np.array([0,1,2,3,4,5])
np2 = np1.view()
np1[2] = 41
print(np1, np2)

[ 0  1 41  3  4  5] [ 0  1 41  3  4  5]


In [26]:
np1 = np.array([0,1,2,3,4,5])
np2 = np1.copy()
np1[2] = 41
print(np1, np2)

[ 0  1 41  3  4  5] [0 1 2 3 4 5]


### **Sorting, Searching, and Filtering**

In [30]:
np1 = np.random.randint(-5, 5, size=(2,8))
print(np1)
print(np.sort(np1))

[[ 1  3 -2  2 -5 -5 -4  2]
 [-1 -3 -5  4  3 -2  3  2]]
[[-5 -5 -4 -2  1  2  2  3]
 [-5 -3 -2 -1  2  3  3  4]]


In [38]:
index = np.where(np1 == 3)
print(index[0], index[1])

[0 1 1] [1 4 6]


In [39]:
index = np.where(np1 % 2 == 0)
print(index[0], index[1])

[0 0 0 0 1 1 1] [2 3 6 7 3 5 7]


In [47]:
filtered1 = np1[index]
print(filtered1)

filter = np1 % 2 == 0
filtered2 = np1[filter]
print(filter)
print(filtered2)

[-2  2 -4  2  4 -2  2]
[[False False  True  True False False  True  True]
 [False False False  True False  True False  True]]
[-2  2 -4  2  4 -2  2]
